-- MySQL Script generated by MySQL Workbench
-- Sun May 16 20:44:29 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema gama
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gama
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gama` DEFAULT CHARACTER SET utf8mb4 ;
USE `gama` ;

-- -----------------------------------------------------
-- Table `gama`.`estados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gama`.`estados` (
  `idEstados` INT NOT NULL AUTO_INCREMENT,
  `siglasEstado` VARCHAR(2) NOT NULL,
  PRIMARY KEY (`idEstados`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gama`.`cidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gama`.`cidades` (
  `idCidade` INT NOT NULL AUTO_INCREMENT,
  `nomeCidade` VARCHAR(100) NOT NULL,
  `estado` INT NOT NULL,
  PRIMARY KEY (`idCidade`),
  INDEX `estadofk_idx` (`estado` ASC) VISIBLE,
  CONSTRAINT `estadofk`
    FOREIGN KEY (`estado`)
    REFERENCES `gama`.`estados` (`idEstados`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gama`.`bairros`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gama`.`bairros` (
  `idbairros` INT NOT NULL AUTO_INCREMENT,
  `nomeBairro` VARCHAR(100) NOT NULL,
  `cidade` INT NOT NULL,
  PRIMARY KEY (`idbairros`),
  INDEX `cidadefk_idx` (`cidade` ASC) VISIBLE,
  CONSTRAINT `cidadefk`
    FOREIGN KEY (`cidade`)
    REFERENCES `gama`.`cidades` (`idCidade`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gama`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gama`.`clientes` (
  `idCliente` INT NOT NULL AUTO_INCREMENT,
  `nomeCliente` VARCHAR(255) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `whatsapp` BIGINT NOT NULL,
  `senha` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`idCliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gama`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gama`.`enderecos` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `tipo` VARCHAR(50) NOT NULL,
  `largadouro` VARCHAR(255) NOT NULL,
  `numero` INT NOT NULL,
  `complemento` VARCHAR(100) NOT NULL,
  `cep` INT NOT NULL,
  `bairro` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `bairrofk_idx` (`bairro` ASC) VISIBLE,
  CONSTRAINT `bairrofk`
    FOREIGN KEY (`bairro`)
    REFERENCES `gama`.`bairros` (`idbairros`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gama`.`clientes_enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gama`.`clientes_enderecos` (
  `cliente` INT NOT NULL,
  `endereco` INT NOT NULL,
  INDEX `clientes_clientes_e_fk` (`cliente` ASC) VISIBLE,
  INDEX `enderecos_clientes_e_fk` (`endereco` ASC) VISIBLE,
  CONSTRAINT `clientes_enderecos_ibfk_1`
    FOREIGN KEY (`cliente`)
    REFERENCES `gama`.`clientes` (`idCliente`),
  CONSTRAINT `clientes_enderecos_ibfk_2`
    FOREIGN KEY (`endereco`)
    REFERENCES `gama`.`enderecos` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gama`.`empresas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gama`.`empresas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nomeEmpresa` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gama`.`departamentos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gama`.`departamentos` (
  `idDepto` INT NOT NULL,
  `nomeDepto` VARCHAR(150) NOT NULL,
  `empresa` INT NOT NULL,
  PRIMARY KEY (`idDepto`),
  INDEX `empresa_departamentos_fk` (`empresa` ASC) VISIBLE,
  CONSTRAINT `departamentos_ibfk_1`
    FOREIGN KEY (`empresa`)
    REFERENCES `gama`.`empresas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gama`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gama`.`pedidos` (
  `numeroPedido` INT NOT NULL,
  `dataPedido` DATE NOT NULL,
  `statusPedido` VARCHAR(100) NOT NULL,
  `ValorTotal` FLOAT NOT NULL,
  `cliente` INT NOT NULL,
  `enderecoEntrega` INT NOT NULL,
  PRIMARY KEY (`numeroPedido`),
  INDEX `cliente_idx` (`cliente` ASC) VISIBLE,
  INDEX `enderecoEntrega_idx` (`enderecoEntrega` ASC) VISIBLE,
  CONSTRAINT `cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `gama`.`clientes_enderecos` (`cliente`),
  CONSTRAINT `enderecoEntrega`
    FOREIGN KEY (`enderecoEntrega`)
    REFERENCES `gama`.`clientes_enderecos` (`endereco`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gama`.`produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gama`.`produtos` (
  `codProduto` INT NOT NULL,
  `descricao` VARCHAR(255) NOT NULL,
  `preco` FLOAT NOT NULL,
  `qtdProduto` INT NOT NULL,
  `disponivel` VARCHAR(3) NOT NULL,
  `emDestaque` VARCHAR(3) NOT NULL,
  `departamento` INT NOT NULL,
  PRIMARY KEY (`codProduto`),
  INDEX `departamentos_produtos_fk` (`departamento` ASC) VISIBLE,
  CONSTRAINT `produtos_ibfk_1`
    FOREIGN KEY (`departamento`)
    REFERENCES `gama`.`departamentos` (`idDepto`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `gama`.`pedidos_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gama`.`pedidos_produtos` (
  `pedido` INT NOT NULL,
  `produto` INT NOT NULL,
  `quantidade` INT NOT NULL,
  `valorUnitario` FLOAT NOT NULL,
  `valorTotal` FLOAT GENERATED ALWAYS AS ((`quantidade` * `valorUnitario`)) STORED,
  INDEX `produtos_pedidos_pr_fk` (`produto` ASC) VISIBLE,
  INDEX `pedidos_pedidos_pr_fk` (`pedido` ASC) VISIBLE,
  CONSTRAINT `pedidos_produtos_ibfk_1`
    FOREIGN KEY (`produto`)
    REFERENCES `gama`.`produtos` (`codProduto`),
  CONSTRAINT `pedidos_produtos_ibfk_2`
    FOREIGN KEY (`pedido`)
    REFERENCES `gama`.`pedidos` (`numeroPedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
